

-- DUMMY.CATEGORIA definition

CREATE TABLE "DUMMY"."CATEGORIA" 
   (	"ID_CATEGORIA" NUMBER DEFAULT "DUMMY"."ID_CATEGORIA"."NEXTVAL" NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100), 
	 CONSTRAINT "CATEGORIA_PK" PRIMARY KEY ("ID_CATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "DUMMY"."CATEGORIA_PK" ON "DUMMY"."CATEGORIA" ("ID_CATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;


-- DUMMY.DEPARTAMENTO definition

CREATE TABLE "DUMMY"."DEPARTAMENTO" 
   (	"ID_DEPARTAMENTO" NUMBER DEFAULT "DUMMY"."ID_DEPARTAMENTO"."NEXTVAL" NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100), 
	"CAPITAL_TOTAL" NUMBER, 
	 CONSTRAINT "DEPARTAMENTO_PK" PRIMARY KEY ("ID_DEPARTAMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "DUMMY"."DEPARTAMENTO_PK" ON "DUMMY"."DEPARTAMENTO" ("ID_DEPARTAMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;


-- DUMMY.FORMATO definition

CREATE TABLE "DUMMY"."FORMATO" 
   (	"ID_FORMATO" NUMBER DEFAULT "DUMMY"."ID_FORMATO"."NEXTVAL" NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100), 
	 CONSTRAINT "FORMATO_PK" PRIMARY KEY ("ID_FORMATO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "DUMMY"."FORMATO_PK" ON "DUMMY"."FORMATO" ("ID_FORMATO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;


-- DUMMY.PRUEBA definition

CREATE TABLE "DUMMY"."PRUEBA" 
   (	"ID_PRUEBA" NUMBER DEFAULT "DUMMY"."ID_PRUEBA"."NEXTVAL" NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100), 
	"EDAD" NUMBER, 
	 PRIMARY KEY ("ID_PRUEBA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "DUMMY"."SYS_C007310" ON "DUMMY"."PRUEBA" ("ID_PRUEBA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


-- DUMMY.PUESTO definition

CREATE TABLE "DUMMY"."PUESTO" 
   (	"ID_PUESTO" NUMBER DEFAULT "DUMMY"."ID_PUESTO"."NEXTVAL" NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100), 
	"SALARIO" NUMBER, 
	 CONSTRAINT "PUESTO_PK" PRIMARY KEY ("ID_PUESTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "DUMMY"."PUESTO_PK" ON "DUMMY"."PUESTO" ("ID_PUESTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;


-- DUMMY.REQUISITO definition

CREATE TABLE "DUMMY"."REQUISITO" 
   (	"ID_REQUISITO" NUMBER DEFAULT "DUMMY"."ID_REQUISITO"."NEXTVAL" NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100), 
	"TAMANO" NUMBER, 
	"OBLIGATORIO" VARCHAR2(100), 
	 CONSTRAINT "REQUISITO_PK" PRIMARY KEY ("ID_REQUISITO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "DUMMY"."REQUISITO_PK" ON "DUMMY"."REQUISITO" ("ID_REQUISITO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;


-- DUMMY.ROL definition

CREATE TABLE "DUMMY"."ROL" 
   (	"ID_ROL" NUMBER DEFAULT "DUMMY"."ID_ROL"."NEXTVAL" NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100), 
	 CONSTRAINT "ROL_PK" PRIMARY KEY ("ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "DUMMY"."ROL_PK" ON "DUMMY"."ROL" ("ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;


-- DUMMY.DEPARTAMENTO_PUESTO definition

CREATE TABLE "DUMMY"."DEPARTAMENTO_PUESTO" 
   (	"ID_DEPARTAMENTO" NUMBER, 
	"ID_PUESTO" NUMBER, 
	 CONSTRAINT "FK_PUESTO_DEPARTAMENTO_PUESTO" FOREIGN KEY ("ID_PUESTO")
	  REFERENCES "DUMMY"."PUESTO" ("ID_PUESTO") ENABLE, 
	 CONSTRAINT "FK_DEPARTAMENTO_DEPARTAMENTO_PUESTO" FOREIGN KEY ("ID_DEPARTAMENTO")
	  REFERENCES "DUMMY"."DEPARTAMENTO" ("ID_DEPARTAMENTO") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


-- DUMMY.PUESTO_CATEGORIA definition

CREATE TABLE "DUMMY"."PUESTO_CATEGORIA" 
   (	"ID_PUESTO" NUMBER, 
	"ID_CATEGORIA" NUMBER, 
	 CONSTRAINT "FK_CATEGORIA" FOREIGN KEY ("ID_CATEGORIA")
	  REFERENCES "DUMMY"."CATEGORIA" ("ID_CATEGORIA") ENABLE, 
	 CONSTRAINT "FK_PUESTO" FOREIGN KEY ("ID_PUESTO")
	  REFERENCES "DUMMY"."PUESTO" ("ID_PUESTO") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


-- DUMMY.PUESTO_REQUISITO definition

CREATE TABLE "DUMMY"."PUESTO_REQUISITO" 
   (	"ID_PUESTO" NUMBER, 
	"ID_REQUISITO" NUMBER, 
	 CONSTRAINT "FK_PUESTO_puesto_requisito" FOREIGN KEY ("ID_PUESTO")
	  REFERENCES "DUMMY"."PUESTO" ("ID_PUESTO") ENABLE, 
	 CONSTRAINT "FK_REQUISITO_puesto_requisito" FOREIGN KEY ("ID_REQUISITO")
	  REFERENCES "DUMMY"."REQUISITO" ("ID_REQUISITO") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


-- DUMMY.REQUISITO_FORMATO definition

CREATE TABLE "DUMMY"."REQUISITO_FORMATO" 
   (	"ID_REQUISITO" NUMBER, 
	"ID_FORMATO" NUMBER, 
	 CONSTRAINT "FK_FORMATO" FOREIGN KEY ("ID_FORMATO")
	  REFERENCES "DUMMY"."FORMATO" ("ID_FORMATO") ENABLE, 
	 CONSTRAINT "FK_REQUISITO" FOREIGN KEY ("ID_REQUISITO")
	  REFERENCES "DUMMY"."REQUISITO" ("ID_REQUISITO") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


-- DUMMY.EMPLEADO definition

CREATE TABLE "DUMMY"."EMPLEADO" 
   (	"ID_EMPLEADO" NUMBER DEFAULT "DUMMY"."ID_EMPLEADO"."NEXTVAL" NOT NULL ENABLE, 
	"USUARIO" VARCHAR2(100), 
	"CONTRASENA" VARCHAR2(100), 
	"FECHA_INICIO" DATE, 
	"FECHA_FIN" DATE, 
	"ESTADO" VARCHAR2(100), 
	"ID_ROL" NUMBER, 
	"ID_DEPARTAMENTO" NUMBER, 
	 CONSTRAINT "EMPLEADO_PK" PRIMARY KEY ("ID_EMPLEADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_ROL" FOREIGN KEY ("ID_ROL")
	  REFERENCES "DUMMY"."ROL" ("ID_ROL") ENABLE, 
	 CONSTRAINT "FK_DEPARTAMENTO" FOREIGN KEY ("ID_DEPARTAMENTO")
	  REFERENCES "DUMMY"."DEPARTAMENTO" ("ID_DEPARTAMENTO") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "DUMMY"."EMPLEADO_PK" ON "DUMMY"."EMPLEADO" ("ID_EMPLEADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;


-- DUMMY.USUARIO definition

CREATE TABLE "DUMMY"."USUARIO" 
   (	"ID_USUARIO" NUMBER DEFAULT "DUMMY"."ID_USUARIO"."NEXTVAL" NOT NULL ENABLE, 
	"ID_ROL" NUMBER, 
	"PRIMER_LOG" VARCHAR2(100), 
	"DPI" VARCHAR2(100), 
	"NOMBRE" VARCHAR2(100), 
	"APELLIDO" VARCHAR2(100), 
	"CORREO" VARCHAR2(100), 
	"DIRECCION" VARCHAR2(100), 
	"TELEFONO" VARCHAR2(100), 
	"ID_EMPLEADO" NUMBER, 
	"CONTRASENA" VARCHAR2(100), 
	 CONSTRAINT "USUARIO_PK" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_EMPLEADO" FOREIGN KEY ("ID_EMPLEADO")
	  REFERENCES "DUMMY"."EMPLEADO" ("ID_EMPLEADO") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "DUMMY"."USUARIO_PK" ON "DUMMY"."USUARIO" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;


-- DUMMY.USUARIO_PUESTO definition

CREATE TABLE "DUMMY"."USUARIO_PUESTO" 
   (	"ID_USUARIO" NUMBER, 
	"ID_PUESTO" NUMBER, 
	"CALIFICACION" NUMBER, 
	"ESTADO" VARCHAR2(100), 
	 CONSTRAINT "FK_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "DUMMY"."USUARIO" ("ID_USUARIO") ENABLE, 
	 CONSTRAINT "FK_PUESTO_USUARIO_PUESTO" FOREIGN KEY ("ID_PUESTO")
	  REFERENCES "DUMMY"."PUESTO" ("ID_PUESTO") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


-- DUMMY.CHAT definition

CREATE TABLE "DUMMY"."CHAT" 
   (	"ID_EMPLEADO" NUMBER, 
	"ID_USUARIO" NUMBER, 
	"MENSAJE" VARCHAR2(100), 
	"FECHA" DATE, 
	 CONSTRAINT "FK_EMPLEADO_CHAT" FOREIGN KEY ("ID_EMPLEADO")
	  REFERENCES "DUMMY"."EMPLEADO" ("ID_EMPLEADO") ENABLE, 
	 CONSTRAINT "FK_USUARIO_CHAT" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "DUMMY"."USUARIO" ("ID_USUARIO") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


-- DUMMY.DOCUMENTO definition

CREATE TABLE "DUMMY"."DOCUMENTO" 
   (	"ID_DOCUMENTO" NUMBER DEFAULT "DUMMY"."ID_DOCUMENTO"."NEXTVAL" NOT NULL ENABLE, 
	"ID_USUARIO" NUMBER, 
	"ESTADO" VARCHAR2(100), 
	"MOTIVO" VARCHAR2(100), 
	"RECHAZOS" NUMBER, 
	"URL" VARCHAR2(100), 
	"EXTENSION" VARCHAR2(100), 
	 CONSTRAINT "DOCUMENTO_PK" PRIMARY KEY ("ID_DOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_USUARIO_DOCUMENTO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "DUMMY"."USUARIO" ("ID_USUARIO") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "DUMMY"."DOCUMENTO_PK" ON "DUMMY"."DOCUMENTO" ("ID_DOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
